const root = document.querySelector(':root')

function dayNightMode(){
  if(gDay){
    root.style.setProperty('--body-bgc','#186d6a')
    root.style.setProperty('--button-bgc', '#0f0f0f')
    root.style.setProperty('--buttons-bos','#00000050')
    root.style.setProperty('--buttons-hover-bgc','#535353')
    root.style.setProperty('--counter-container-border', '#0f0f0f')
    root.style.setProperty('--hearts-color','#ca2e2e')
    root.style.setProperty('--leaderboard-bgc','#443333a5')
    root.style.setProperty('--leaderboard-col','#7ba1c5')
    root.style.setProperty('--leaderboard-bos-inner','#00000080')
    root.style.setProperty('--leaderboard-bos-outer','#ffffff80')
    root.style.setProperty('--shown-bgc','#757a75')
    root.style.setProperty('--marked-bgc','#617e9b')
    root.style.setProperty('--losing-bgc','#c43131')
    root.style.setProperty('--losing-bos','#4e0a0a80')
    root.style.setProperty('--missed-bgc','#3cf5ec')
    root.style.setProperty('--win-marked-bgc','#229122')
    root.style.setProperty('--selected-bgc','#ffa500')
    root.style.setProperty('--selected-bos','#ffa50080')
    gDay = !gDay
    return
  }
  root.style.setProperty('--body-bgc','#0f0f0f')
  root.style.setProperty('--button-bgc', '#186d6a')
  root.style.setProperty('--buttons-bos','#ffffff4d')
  root.style.setProperty('--buttons-hover-bgc','#9a9a9a')
  root.style.setProperty('--counter-container-border', '#eee')
  root.style.setProperty('--hearts-color','#ff0000')
  root.style.setProperty('--leaderboard-bgc','#6b6b6ba5')
  root.style.setProperty('--leaderboard-col','#87a0b7')
  root.style.setProperty('--leaderboard-bos-inner','#00000080')
  root.style.setProperty('--leaderboard-bos-outer','#ffffff80')
  root.style.setProperty('--shown-bgc','#939892')
  root.style.setProperty('--marked-bgc','#324558')
  root.style.setProperty('--losing-bgc','#5e2323')
  root.style.setProperty('--losing-bos','#ff010180')
  root.style.setProperty('--missed-bgc','#20b2aa')
  root.style.setProperty('--win-marked-bgc','#008000')
  root.style.setProperty('--selected-bgc','#ffa500')
  root.style.setProperty('--selected-bos','#ffa50080')
  gDay = !gDay
}